type FormElement = HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement;

export interface FillResult {
  fieldId: string;
  label: string;
  filled: boolean;
  value?: string;
  reason?: string; // Why it wasn't filled (e.g., "No answer from AI", "Element not found")
}

function handleSelectElement(element: HTMLSelectElement, value: string): void {
  let matched = false;
  for (let i = 0; i < element.options.length; i++) {
    const option = element.options[i];
    if (option && (option.text.trim() === value.trim() || option.value === value.trim())) {
      element.selectedIndex = i;
      matched = true;
      break;
    }
  }
  if (!matched) {
    console.warn(`[JobSA] Could not find exact select option for "${value}" on #${element.id}`);
  }
}

function handleCheckableElement(element: HTMLInputElement, value: string): void {
  const normalizedValue = value.toLowerCase();
  element.checked = normalizedValue === 'true' || normalizedValue === 'yes' || normalizedValue === '1';
}

function triggerFrameworkEvents(element: FormElement): void {
  element.dispatchEvent(new Event('input', { bubbles: true }));
  element.dispatchEvent(new Event('change', { bubbles: true }));
  
  // React 16+ specific hack for forcing events
  const tracker = (element as any)._valueTracker;
  if (tracker) {
    tracker.setValue(element.value);
  }
}

export function injectAnswers(
  answers: Record<string, string>,
  extractedFields: Array<{ id: string; label: string }>
): FillResult[] {
  const results: FillResult[] = [];

  for (const field of extractedFields) {
    const value = answers[field.id];

    // No answer from backend for this field
    if (!value) {
      results.push({
        fieldId: field.id,
        label: field.label,
        filled: false,
        reason: "No answer generated by AI"
      });
      continue;
    }

    const element = document.getElementById(field.id) as FormElement | null;
    if (!element) {
      results.push({
        fieldId: field.id,
        label: field.label,
        filled: false,
        value,
        reason: "Form element not found on page"
      });
      continue;
    }

    // Attempt to fill
    if (element.tagName.toLowerCase() === 'select') {
      handleSelectElement(element as HTMLSelectElement, value);
    } else if (element.type === 'checkbox' || element.type === 'radio') {
      handleCheckableElement(element as HTMLInputElement, value);
    } else {
      element.value = value;
    }

    triggerFrameworkEvents(element);

    results.push({
      fieldId: field.id,
      label: field.label,
      filled: true,
      value
    });
  }

  return results;
}
